principal : Coordenada.o exercise1.o
    g++ Coordenada.o exercise1.o -o exercise1
Coordenada.o : Coordenada.cc Coordenada.h
    g++ Coordenada.cc -c
exercise1.o : exercise1.cc Coordenada.h
    g++ exercise1.cc -c
